stages:
  - checks
  - deploy

default:
  tags: [GEAU]

image: rocker/geospatial:latest

variables:
  CI_CACHE_DIR: "$CI_PROJECT_DIR/ci"
  R_LIBS_USER: "$CI_CACHE_DIR/lib"
  BRANCH_PAGES: "gitlab-pages"
  COVERAGE_REPORT: "$CI_CACHE_DIR/coverage.RDS"

cache:
  key:
  paths:
    - $CI_CACHE_DIR

.default_build:
  before_script:
    - mkdir -p $R_LIBS_USER
    - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
    - echo "R_LIBS_USER='$R_LIBS_USER'" >> .Renviron
    - echo "options(repos = c(INRAE = 'https://inrae.r-universe.dev', getOption('repos')))" > .Rprofile
    - R -q -e 'if (!require(devtools)) install.packages("devtools")'
    - R -q -e 'if (!require(pak)) install.packages("pak")'
    - R -q -e 'pak::local_install(upgrade = TRUE, dependencies = TRUE)'

check:
  rules:
    - if: '$CI_COMMIT_BRANCH == "gitlab-pages" || $CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - when: never
  extends: .default_build
  variables:
    NOT_CRAN: "true"
    _R_CHECK_FUTURE_FILE_TIMESTAMPS_: "false"
  stage: checks
  script:
    - R -q -e 'devtools::check(vignettes = TRUE, error_on = "error")'

scheduled_tests:
  extends: .default_build
  stage: checks
  cache: {}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - when: never
  script:
    - R -q -e '"happign" %in% rownames(installed.packages())'
    - R -q -e 'installed.packages()["happign", "LibPath"]'
    - ls -la $CI_CACHE_DIR/lib/happign
    - R -q -e 'devtools::test(stop_on_failure = TRUE)'

coverage:
  stage: checks
  allow_failure: true
  extends: .default_build
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"'
  script:
    - Rscript -e 'devtools::install()'
    - Rscript -e 'install.packages(c("covr", "DT"))'
    - Rscript -e 'cov <- covr::package_coverage(type = "all", quiet = FALSE);cov;saveRDS(cov, Sys.getenv("COVERAGE_REPORT"))'
  artifacts:
    paths:
      - ci/coverage.RDS
  coverage: '/CAWET Coverage: (\d+)\.\d+%/'

.deploy:
  rules:
      - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'
      - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"'
  artifacts:
    paths:
      - public/

pkgdown:
  extends:
    - .default_build
    - .deploy
  stage: deploy
  needs:
    - job: coverage
      artifacts: true
  script:
    - R -q -e 'if (!require(pkgdown)) install.packages("pkgdown")'
    - test "$CI_COMMIT_BRANCH" = "main" && export PKGDOWN_DEV_MODE="release" || export PKGDOWN_DEV_MODE="devel"
    - R -q -e 'pkgdown::build_site()'
    - R -q -e 'install.packages(c("covr", "DT"))'
    - R -q -e 'covr::report(readRDS(Sys.getenv("COVERAGE_REPORT")), "public/coverage.html")'

pages:
  extends: .deploy
  stage: deploy
  pages: true  # specifies that this is a Pages job and publishes the default public directory
  needs:
    - job: pkgdown
      artifacts: true
  script:
    - git add -f public
    - git config --global user.email "gitlab-ci@inrae.fr"
    - git config --global user.name "GitLab CI"
    - git commit -m "Update GitLab pages"

    # Capture the current commit hash for cherry-picking
    - HASH_COMMIT_PAGES="$(git rev-parse HEAD)"

    # Set remote URL for pushing changes
    - git remote set-url origin https://whatever:${READ_WRITE_REPO_ACCESS_TOKEN}@forge.inrae.fr/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git

    # Checkout or create the branch
    - |
      if git ls-remote --exit-code --heads origin "$BRANCH_PAGES" > /dev/null; then
        echo "Remote branch '$BRANCH_PAGES' exists. Checking out and resetting."
        git fetch origin "$BRANCH_PAGES"
        git checkout -B "$BRANCH_PAGES" origin/"$BRANCH_PAGES"
      else
        echo "Remote branch '$BRANCH_PAGES' does not exist. Creating new local branch."
        git checkout -b "$BRANCH_PAGES"
        find . -maxdepth 1 -mindepth 1 ! -name public ! -name .git ! -name ci -exec rm -rf {} +
        git add .
        git commit -m "gitlab-pages initialization"
      fi

    # Cherry-pick the latest commit to the new branch
    - |
      git cherry-pick "$HASH_COMMIT_PAGES" --strategy-option theirs || \
        (if git status | grep -q 'You are currently cherry-picking'; then
          echo "Cherry-pick resulted in empty commit. Skipping."
          git cherry-pick --skip
        else
          echo "Cherry-pick failed unexpectedly." >&2
          exit 1
        fi)

    # Push the changes to the remote
    - git push --set-upstream origin "$BRANCH_PAGES"
